schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "ETLCPP__etl-1334"
repository = "ETLCPP/etl"
language = "c++"
base_commit = "12cdbc0da02e84a94a66ead292f34093356d92ea"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:ETLCPP__etl-1334"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 40960
gpus = 0
