schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "0xMiden__miden-vm-c_5a9834d"
repository = "0xMiden/miden-vm"
language = "rust"
base_commit = "9f98be9a80a65d335b313e2caad402db8a8dc5be"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:0xMiden__miden-vm-c_5a9834d"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 30720
gpus = 0
