schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "lerd-env__lerd-471"
repository = "lerd-env/lerd"
language = "go"
base_commit = "5741e56605430a2b3be05f23c4a504952e1101f7"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:lerd-env__lerd-471"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 20480
gpus = 0
