schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "qicosmos__iguana-383"
repository = "qicosmos/iguana"
language = "c++"
base_commit = "15931f44139a740f0a19917ec8414fe6e7ba3c51"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:qicosmos__iguana-383"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 40960
gpus = 0
