schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "langchain-ai__openwiki-c_60f7877"
repository = "langchain-ai/openwiki"
language = "typescript"
base_commit = "5a2e8dc569bbcab48728c65f8e1ffe8980f04dbf"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:langchain-ai__openwiki-c_60f7877"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 20480
gpus = 0
