schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "jhao104__proxy_pool-c_9dc9bed"
repository = "jhao104/proxy_pool"
language = "python"
base_commit = "c6116b7650645f0894e9fb03ae74ba8ae9ef7ed7"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:jhao104__proxy_pool-c_9dc9bed"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 20480
gpus = 0
