schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "janosmiko__lfk-578"
repository = "janosmiko/lfk"
language = "go"
base_commit = "6ef32eaf81ffaeefa90ff35c5bd556b58ff95f49"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:janosmiko__lfk-578"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 20480
gpus = 0
