schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "microsoft__agent-framework-go-110"
repository = "microsoft/agent-framework-go"
language = "go"
base_commit = "543cf17875d52b11abcc664559d1c35cdcc0f4fb"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:microsoft__agent-framework-go-110"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 20480
gpus = 0
