schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "RakuenSoftware__aimee-c_1c60c9c"
repository = "RakuenSoftware/aimee"
language = "c"
base_commit = "16acf2b62519988d21c3c65f856e060eb33cce1e"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:RakuenSoftware__aimee-c_1c60c9c"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 40960
gpus = 0
