schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "letta-ai__letta-code-2798"
repository = "letta-ai/letta-code"
language = "typescript"
base_commit = "43aa4ee70877b3890f0bd732aeb568a8f2e92bd5"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:letta-ai__letta-code-2798"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 20480
gpus = 0
