schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "basicmachines-co__basic-memory-1102"
repository = "basicmachines-co/basic-memory"
language = "python"
base_commit = "35a7f5a52581b4a47b449dac00c78bb035dc1258"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:basicmachines-co__basic-memory-1102"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 20480
gpus = 0
