schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "lucianodato__libspecbleach-90"
repository = "lucianodato/libspecbleach"
language = "c"
base_commit = "2f83af84c4877bb0241c1f8c13a50136f56d53ef"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:lucianodato__libspecbleach-90"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 40960
gpus = 0
