schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "xremap__xremap-892"
repository = "xremap/xremap"
language = "rust"
base_commit = "b259225a266f17a874294a010227ca8a3b76b0eb"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:xremap__xremap-892"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 30720
gpus = 0
