schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "aldinokemal__go-whatsapp-web-multidevice-710"
repository = "aldinokemal/go-whatsapp-web-multidevice"
language = "go"
base_commit = "0c818797e740e073710208c7443ca10b50c5a721"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:aldinokemal__go-whatsapp-web-multidevice-710"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 20480
gpus = 0
