schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "lumina-layer-studio__Lumina-Layers-c_2442e44"
repository = "lumina-layer-studio/Lumina-Layers"
language = "python"
base_commit = "6f3325e8d1f4a22747edbedaace462ef48fcf3f3"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:lumina-layer-studio__Lumina-Layers-c_2442e44"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 20480
gpus = 0
