schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "openmemind__memind-2"
repository = "openmemind/memind"
language = "java"
base_commit = "6f9a4c650de94ad12afe47400328988005b91533"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:openmemind__memind-2"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 40960
gpus = 0
