schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "GizClaw__flowcraft-84"
repository = "GizClaw/flowcraft"
language = "go"
base_commit = "5c4e7b408bd2fb4f23d40b41110469bfad2c0256"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:GizClaw__flowcraft-84"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 20480
gpus = 0
