schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "cmu-phil__tetrad-c_5a3d308"
repository = "cmu-phil/tetrad"
language = "java"
base_commit = "55a93d2b561346f8164f080809223ae511200eae"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:cmu-phil__tetrad-c_5a3d308"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 40960
gpus = 0
