schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "RakuenSoftware__aimee-c_d9e4faf"
repository = "RakuenSoftware/aimee"
language = "c"
base_commit = "49b027d690c9164f459226b1ce36a3b86a4e2fb2"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:RakuenSoftware__aimee-c_d9e4faf"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 40960
gpus = 0
