schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "google-gemini__gemini-cli-21776"
repository = "google-gemini/gemini-cli"
language = "typescript"
base_commit = "b89944c3a3c5c1626f8afd4a196f5280340a2760"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:google-gemini__gemini-cli-21776"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 20480
gpus = 0
