schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "noctalia-dev__noctalia-c_13931d8"
repository = "noctalia-dev/noctalia"
language = "c++"
base_commit = "20971a4caebe507ed71105d92ac277e427a6a117"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:noctalia-dev__noctalia-c_13931d8"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 40960
gpus = 0
