schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "tailcallhq__forgecode-2716"
repository = "tailcallhq/forgecode"
language = "rust"
base_commit = "d02477e4973e206d190447ec0a5428e88a482f48"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:tailcallhq__forgecode-2716"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 30720
gpus = 0
