schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "Mrmayman__quantumlauncher-c_fb3452c"
repository = "Mrmayman/quantumlauncher"
language = "rust"
base_commit = "09106e4ec5cb6d1213a2c021ad3dc692934c3c0b"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:Mrmayman__quantumlauncher-c_fb3452c"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 30720
gpus = 0
