schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "monkeytypegame__monkeytype-8134"
repository = "monkeytypegame/monkeytype"
language = "typescript"
base_commit = "a7ee6c9be33714fe25c213efcd2f4ff4c9ff007f"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:monkeytypegame__monkeytype-8134"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 20480
gpus = 0
