schema_version = "1.0"

[metadata]
benchmark = "swepmv2"
instance_id = "RakuenSoftware__aimee-2581"
repository = "RakuenSoftware/aimee"
language = "c"
base_commit = "14caf9e0d56d99e0119ad46624b33e4baaf20930"
category = "debugging"

[verifier]
timeout_sec = 3600.0

[agent]
timeout_sec = 7200.0

[environment]
build_timeout_sec = 1800.0
docker_image = "key4127/refactor-dockerhub:RakuenSoftware__aimee-2581"
workdir = "/testbed"
cpus = 4
memory_mb = 32768
storage_mb = 40960
gpus = 0
